[package]
name = "c-usersanzelappdatalocaltempaltnote-scaffold"
version = "1.1.0"
description = "A windows notepad replacement"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "c_usersanzelappdatalocaltempaltnote_scaffold_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-dialog = "2.7.2"
tauri-plugin-fs = "2.5.1"
tauri-plugin-store = "2.4.4"
font-kit = "0.14.3"
reqwest = "0.13.4"
flate2 = "1.1.9"
zip = "8.6.0"
jsonc-parser = { version = "0.33.1", features = ["serde"] }
tauri-plugin-persisted-scope = "2.3.7"
tauri-plugin-single-instance = "2"
urlencoding = "2"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true

